# Generated by Django 2.1.5 on 2019-04-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinishItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.BigIntegerField(default=0, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('shop_name', models.CharField(max_length=25)),
                ('analyse_time', models.DateTimeField(auto_now_add=True)),
                ('paltform', models.CharField(max_length=4)),
                ('comments', models.IntegerField(default=0)),
                ('good_percent', models.FloatField(default=0)),
                ('image_url', models.CharField(default='static/images/item/example.jpg', max_length=255)),
            ],
        ),
    ]
